syntax = "proto3";

package order.v1;

import "contracts/common/v1/metadata.proto";

option go_package = "contracts/order/v1;order";

// Order placed → reserve inventory
message OrderPlaced {
  common.v1.EventMetadata metadata = 1;

  string order_id = 2;
  string warehouse_id = 3; // warehouse or store
  string sku = 4;
  int64 quantity = 5;
}

// Order cancelled → release inventory
message OrderCancelled {
  common.v1.EventMetadata metadata = 1;

  string order_id = 2;
  string warehouse_id = 3;
  string sku = 4;
  int64 quantity = 5;
}

message OrderShipped {
  common.v1.EventMetadata metadata = 1;

  string order_id = 2;
  string warehouse_id = 3;
  string sku = 4;
  int64 quantity = 5;
}
