syntax = "proto3";

package sales.v1;

import "contracts/common/v1/metadata.proto";

option go_package = "contracts/sales/v1;sales";

message SaleCompleted {
  common.v1.EventMetadata metadata = 1;

  string sale_id = 2;
  string store_id = 3;
  string sku = 4;
  int64 quantity = 5;
}

//====================================================================================================

// Sale initiated (optional, for reservation)
message SaleStarted {
  common.v1.EventMetadata metadata = 1;

  string sale_id = 2;
  string store_id = 3;
}

// Sale refunded → restore inventory
message SaleRefunded {
  common.v1.EventMetadata metadata = 1;

  string sale_id = 2;
  string store_id = 3;
}
