// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contracts/sales/v1/sale_events.proto

package sales

import (
	v1 "github.com/kamogelosekhukhune777/real-time-supply-chain/services/inventory/internal/service/events/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaleCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SaleId        string                 `protobuf:"bytes,2,opt,name=sale_id,json=saleId,proto3" json:"sale_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,3,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaleCompleted) Reset() {
	*x = SaleCompleted{}
	mi := &file_contracts_sales_v1_sale_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaleCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleCompleted) ProtoMessage() {}

func (x *SaleCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_sales_v1_sale_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleCompleted.ProtoReflect.Descriptor instead.
func (*SaleCompleted) Descriptor() ([]byte, []int) {
	return file_contracts_sales_v1_sale_events_proto_rawDescGZIP(), []int{0}
}

func (x *SaleCompleted) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SaleCompleted) GetSaleId() string {
	if x != nil {
		return x.SaleId
	}
	return ""
}

func (x *SaleCompleted) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *SaleCompleted) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *SaleCompleted) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_contracts_sales_v1_sale_events_proto protoreflect.FileDescriptor

const file_contracts_sales_v1_sale_events_proto_rawDesc = "" +
	"\n" +
	"$contracts/sales/v1/sale_events.proto\x12\bsales.v1\x1a\"contracts/common/v1/metadata.proto\"\xa7\x01\n" +
	"\rSaleCompleted\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x17\n" +
	"\asale_id\x18\x02 \x01(\tR\x06saleId\x12\x19\n" +
	"\bstore_id\x18\x03 \x01(\tR\astoreId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantityB\x1aZ\x18contracts/sales/v1;salesb\x06proto3"

var (
	file_contracts_sales_v1_sale_events_proto_rawDescOnce sync.Once
	file_contracts_sales_v1_sale_events_proto_rawDescData []byte
)

func file_contracts_sales_v1_sale_events_proto_rawDescGZIP() []byte {
	file_contracts_sales_v1_sale_events_proto_rawDescOnce.Do(func() {
		file_contracts_sales_v1_sale_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_sales_v1_sale_events_proto_rawDesc), len(file_contracts_sales_v1_sale_events_proto_rawDesc)))
	})
	return file_contracts_sales_v1_sale_events_proto_rawDescData
}

var file_contracts_sales_v1_sale_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contracts_sales_v1_sale_events_proto_goTypes = []any{
	(*SaleCompleted)(nil),    // 0: sales.v1.SaleCompleted
	(*v1.EventMetadata)(nil), // 1: common.v1.EventMetadata
}
var file_contracts_sales_v1_sale_events_proto_depIdxs = []int32{
	1, // 0: sales.v1.SaleCompleted.metadata:type_name -> common.v1.EventMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_sales_v1_sale_events_proto_init() }
func file_contracts_sales_v1_sale_events_proto_init() {
	if File_contracts_sales_v1_sale_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_sales_v1_sale_events_proto_rawDesc), len(file_contracts_sales_v1_sale_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_sales_v1_sale_events_proto_goTypes,
		DependencyIndexes: file_contracts_sales_v1_sale_events_proto_depIdxs,
		MessageInfos:      file_contracts_sales_v1_sale_events_proto_msgTypes,
	}.Build()
	File_contracts_sales_v1_sale_events_proto = out.File
	file_contracts_sales_v1_sale_events_proto_goTypes = nil
	file_contracts_sales_v1_sale_events_proto_depIdxs = nil
}
