// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contracts/optimization/v1/optimization_events.proto

package optimization

import (
	v1 "github.com/kamogelosekhukhune777/real-time-supply-chain/services/inventory/internal/service/events/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionType int32

const (
	DecisionType_DECISION_TYPE_UNSPECIFIED DecisionType = 0
	DecisionType_REALLOCATE_STOCK          DecisionType = 1
	DecisionType_REROUTE_SHIPMENT          DecisionType = 2
)

// Enum value maps for DecisionType.
var (
	DecisionType_name = map[int32]string{
		0: "DECISION_TYPE_UNSPECIFIED",
		1: "REALLOCATE_STOCK",
		2: "REROUTE_SHIPMENT",
	}
	DecisionType_value = map[string]int32{
		"DECISION_TYPE_UNSPECIFIED": 0,
		"REALLOCATE_STOCK":          1,
		"REROUTE_SHIPMENT":          2,
	}
)

func (x DecisionType) Enum() *DecisionType {
	p := new(DecisionType)
	*p = x
	return p
}

func (x DecisionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DecisionType) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_optimization_v1_optimization_events_proto_enumTypes[0].Descriptor()
}

func (DecisionType) Type() protoreflect.EnumType {
	return &file_contracts_optimization_v1_optimization_events_proto_enumTypes[0]
}

func (x DecisionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DecisionType.Descriptor instead.
func (DecisionType) EnumDescriptor() ([]byte, []int) {
	return file_contracts_optimization_v1_optimization_events_proto_rawDescGZIP(), []int{0}
}

type OptimizationDecisionCreated struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Metadata         *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DecisionId       string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Type             DecisionType           `protobuf:"varint,3,opt,name=type,proto3,enum=optimization.v1.DecisionType" json:"type,omitempty"`
	Reason           string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence       float32                `protobuf:"fixed32,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AffectedEntityId string                 `protobuf:"bytes,6,opt,name=affected_entity_id,json=affectedEntityId,proto3" json:"affected_entity_id,omitempty"` // shipment_id or warehouse_id
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OptimizationDecisionCreated) Reset() {
	*x = OptimizationDecisionCreated{}
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationDecisionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationDecisionCreated) ProtoMessage() {}

func (x *OptimizationDecisionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationDecisionCreated.ProtoReflect.Descriptor instead.
func (*OptimizationDecisionCreated) Descriptor() ([]byte, []int) {
	return file_contracts_optimization_v1_optimization_events_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizationDecisionCreated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OptimizationDecisionCreated) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *OptimizationDecisionCreated) GetType() DecisionType {
	if x != nil {
		return x.Type
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

func (x *OptimizationDecisionCreated) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OptimizationDecisionCreated) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *OptimizationDecisionCreated) GetAffectedEntityId() string {
	if x != nil {
		return x.AffectedEntityId
	}
	return ""
}

// decision successfully applied
type OptimizationDecisionExecuted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Type          DecisionType           `protobuf:"varint,3,opt,name=type,proto3,enum=optimization.v1.DecisionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationDecisionExecuted) Reset() {
	*x = OptimizationDecisionExecuted{}
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationDecisionExecuted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationDecisionExecuted) ProtoMessage() {}

func (x *OptimizationDecisionExecuted) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationDecisionExecuted.ProtoReflect.Descriptor instead.
func (*OptimizationDecisionExecuted) Descriptor() ([]byte, []int) {
	return file_contracts_optimization_v1_optimization_events_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizationDecisionExecuted) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OptimizationDecisionExecuted) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *OptimizationDecisionExecuted) GetType() DecisionType {
	if x != nil {
		return x.Type
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

// decision rejected or failed
type OptimizationDecisionFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Type          DecisionType           `protobuf:"varint,3,opt,name=type,proto3,enum=optimization.v1.DecisionType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationDecisionFailed) Reset() {
	*x = OptimizationDecisionFailed{}
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationDecisionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationDecisionFailed) ProtoMessage() {}

func (x *OptimizationDecisionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_optimization_v1_optimization_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationDecisionFailed.ProtoReflect.Descriptor instead.
func (*OptimizationDecisionFailed) Descriptor() ([]byte, []int) {
	return file_contracts_optimization_v1_optimization_events_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizationDecisionFailed) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OptimizationDecisionFailed) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *OptimizationDecisionFailed) GetType() DecisionType {
	if x != nil {
		return x.Type
	}
	return DecisionType_DECISION_TYPE_UNSPECIFIED
}

var File_contracts_optimization_v1_optimization_events_proto protoreflect.FileDescriptor

const file_contracts_optimization_v1_optimization_events_proto_rawDesc = "" +
	"\n" +
	"3contracts/optimization/v1/optimization_events.proto\x12\x0foptimization.v1\x1a\"contracts/common/v1/metadata.proto\"\x8d\x02\n" +
	"\x1bOptimizationDecisionCreated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.optimization.v1.DecisionTypeR\x04type\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x02R\n" +
	"confidence\x12,\n" +
	"\x12affected_entity_id\x18\x06 \x01(\tR\x10affectedEntityId\"\xa8\x01\n" +
	"\x1cOptimizationDecisionExecuted\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.optimization.v1.DecisionTypeR\x04type\"\xa6\x01\n" +
	"\x1aOptimizationDecisionFailed\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.optimization.v1.DecisionTypeR\x04type*Y\n" +
	"\fDecisionType\x12\x1d\n" +
	"\x19DECISION_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REALLOCATE_STOCK\x10\x01\x12\x14\n" +
	"\x10REROUTE_SHIPMENT\x10\x02B(Z&contracts/optimization/v1;optimizationb\x06proto3"

var (
	file_contracts_optimization_v1_optimization_events_proto_rawDescOnce sync.Once
	file_contracts_optimization_v1_optimization_events_proto_rawDescData []byte
)

func file_contracts_optimization_v1_optimization_events_proto_rawDescGZIP() []byte {
	file_contracts_optimization_v1_optimization_events_proto_rawDescOnce.Do(func() {
		file_contracts_optimization_v1_optimization_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_optimization_v1_optimization_events_proto_rawDesc), len(file_contracts_optimization_v1_optimization_events_proto_rawDesc)))
	})
	return file_contracts_optimization_v1_optimization_events_proto_rawDescData
}

var file_contracts_optimization_v1_optimization_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_optimization_v1_optimization_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contracts_optimization_v1_optimization_events_proto_goTypes = []any{
	(DecisionType)(0),                    // 0: optimization.v1.DecisionType
	(*OptimizationDecisionCreated)(nil),  // 1: optimization.v1.OptimizationDecisionCreated
	(*OptimizationDecisionExecuted)(nil), // 2: optimization.v1.OptimizationDecisionExecuted
	(*OptimizationDecisionFailed)(nil),   // 3: optimization.v1.OptimizationDecisionFailed
	(*v1.EventMetadata)(nil),             // 4: common.v1.EventMetadata
}
var file_contracts_optimization_v1_optimization_events_proto_depIdxs = []int32{
	4, // 0: optimization.v1.OptimizationDecisionCreated.metadata:type_name -> common.v1.EventMetadata
	0, // 1: optimization.v1.OptimizationDecisionCreated.type:type_name -> optimization.v1.DecisionType
	4, // 2: optimization.v1.OptimizationDecisionExecuted.metadata:type_name -> common.v1.EventMetadata
	0, // 3: optimization.v1.OptimizationDecisionExecuted.type:type_name -> optimization.v1.DecisionType
	4, // 4: optimization.v1.OptimizationDecisionFailed.metadata:type_name -> common.v1.EventMetadata
	0, // 5: optimization.v1.OptimizationDecisionFailed.type:type_name -> optimization.v1.DecisionType
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_contracts_optimization_v1_optimization_events_proto_init() }
func file_contracts_optimization_v1_optimization_events_proto_init() {
	if File_contracts_optimization_v1_optimization_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_optimization_v1_optimization_events_proto_rawDesc), len(file_contracts_optimization_v1_optimization_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_optimization_v1_optimization_events_proto_goTypes,
		DependencyIndexes: file_contracts_optimization_v1_optimization_events_proto_depIdxs,
		EnumInfos:         file_contracts_optimization_v1_optimization_events_proto_enumTypes,
		MessageInfos:      file_contracts_optimization_v1_optimization_events_proto_msgTypes,
	}.Build()
	File_contracts_optimization_v1_optimization_events_proto = out.File
	file_contracts_optimization_v1_optimization_events_proto_goTypes = nil
	file_contracts_optimization_v1_optimization_events_proto_depIdxs = nil
}
