// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contracts/demand/v1/forecast_events.proto

package demand

import (
	v1 "github.com/kamogelosekhukhune777/real-time-supply-chain/services/inventory/internal/service/events/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DemandForecastUpdated_RiskLevel int32

const (
	DemandForecastUpdated_UNKNOWN DemandForecastUpdated_RiskLevel = 0
	DemandForecastUpdated_LOW     DemandForecastUpdated_RiskLevel = 1
	DemandForecastUpdated_MEDIUM  DemandForecastUpdated_RiskLevel = 2
	DemandForecastUpdated_HIGH    DemandForecastUpdated_RiskLevel = 3
)

// Enum value maps for DemandForecastUpdated_RiskLevel.
var (
	DemandForecastUpdated_RiskLevel_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
	}
	DemandForecastUpdated_RiskLevel_value = map[string]int32{
		"UNKNOWN": 0,
		"LOW":     1,
		"MEDIUM":  2,
		"HIGH":    3,
	}
)

func (x DemandForecastUpdated_RiskLevel) Enum() *DemandForecastUpdated_RiskLevel {
	p := new(DemandForecastUpdated_RiskLevel)
	*p = x
	return p
}

func (x DemandForecastUpdated_RiskLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DemandForecastUpdated_RiskLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_demand_v1_forecast_events_proto_enumTypes[0].Descriptor()
}

func (DemandForecastUpdated_RiskLevel) Type() protoreflect.EnumType {
	return &file_contracts_demand_v1_forecast_events_proto_enumTypes[0]
}

func (x DemandForecastUpdated_RiskLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DemandForecastUpdated_RiskLevel.Descriptor instead.
func (DemandForecastUpdated_RiskLevel) EnumDescriptor() ([]byte, []int) {
	return file_contracts_demand_v1_forecast_events_proto_rawDescGZIP(), []int{0, 0}
}

type DemandForecastUpdated struct {
	state                protoimpl.MessageState          `protogen:"open.v1"`
	Metadata             *v1.EventMetadata               `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LocationId           string                          `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"` // store or warehouse
	Sku                  string                          `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ForecastHorizonHours int64                           `protobuf:"varint,4,opt,name=forecast_horizon_hours,json=forecastHorizonHours,proto3" json:"forecast_horizon_hours,omitempty"`
	PredictedDemand      int64                           `protobuf:"varint,5,opt,name=predicted_demand,json=predictedDemand,proto3" json:"predicted_demand,omitempty"`
	Risk                 DemandForecastUpdated_RiskLevel `protobuf:"varint,6,opt,name=risk,proto3,enum=demand.v1.DemandForecastUpdated_RiskLevel" json:"risk,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DemandForecastUpdated) Reset() {
	*x = DemandForecastUpdated{}
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandForecastUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandForecastUpdated) ProtoMessage() {}

func (x *DemandForecastUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandForecastUpdated.ProtoReflect.Descriptor instead.
func (*DemandForecastUpdated) Descriptor() ([]byte, []int) {
	return file_contracts_demand_v1_forecast_events_proto_rawDescGZIP(), []int{0}
}

func (x *DemandForecastUpdated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DemandForecastUpdated) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *DemandForecastUpdated) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *DemandForecastUpdated) GetForecastHorizonHours() int64 {
	if x != nil {
		return x.ForecastHorizonHours
	}
	return 0
}

func (x *DemandForecastUpdated) GetPredictedDemand() int64 {
	if x != nil {
		return x.PredictedDemand
	}
	return 0
}

func (x *DemandForecastUpdated) GetRisk() DemandForecastUpdated_RiskLevel {
	if x != nil {
		return x.Risk
	}
	return DemandForecastUpdated_UNKNOWN
}

// emitted when demand exceeds normal variance
type DemandSpikeDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandSpikeDetected) Reset() {
	*x = DemandSpikeDetected{}
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandSpikeDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandSpikeDetected) ProtoMessage() {}

func (x *DemandSpikeDetected) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandSpikeDetected.ProtoReflect.Descriptor instead.
func (*DemandSpikeDetected) Descriptor() ([]byte, []int) {
	return file_contracts_demand_v1_forecast_events_proto_rawDescGZIP(), []int{1}
}

func (x *DemandSpikeDetected) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DemandSpikeDetected) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *DemandSpikeDetected) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// emitted when demand implies replenishment
type DemandReorderTriggered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemandReorderTriggered) Reset() {
	*x = DemandReorderTriggered{}
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemandReorderTriggered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemandReorderTriggered) ProtoMessage() {}

func (x *DemandReorderTriggered) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_demand_v1_forecast_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemandReorderTriggered.ProtoReflect.Descriptor instead.
func (*DemandReorderTriggered) Descriptor() ([]byte, []int) {
	return file_contracts_demand_v1_forecast_events_proto_rawDescGZIP(), []int{2}
}

func (x *DemandReorderTriggered) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DemandReorderTriggered) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *DemandReorderTriggered) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

var File_contracts_demand_v1_forecast_events_proto protoreflect.FileDescriptor

const file_contracts_demand_v1_forecast_events_proto_rawDesc = "" +
	"\n" +
	")contracts/demand/v1/forecast_events.proto\x12\tdemand.v1\x1a\"contracts/common/v1/metadata.proto\"\xda\x02\n" +
	"\x15DemandForecastUpdated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x124\n" +
	"\x16forecast_horizon_hours\x18\x04 \x01(\x03R\x14forecastHorizonHours\x12)\n" +
	"\x10predicted_demand\x18\x05 \x01(\x03R\x0fpredictedDemand\x12>\n" +
	"\x04risk\x18\x06 \x01(\x0e2*.demand.v1.DemandForecastUpdated.RiskLevelR\x04risk\"7\n" +
	"\tRiskLevel\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\"~\n" +
	"\x13DemandSpikeDetected\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"\x81\x01\n" +
	"\x16DemandReorderTriggered\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03skuB\x1cZ\x1acontracts/demand/v1;demandb\x06proto3"

var (
	file_contracts_demand_v1_forecast_events_proto_rawDescOnce sync.Once
	file_contracts_demand_v1_forecast_events_proto_rawDescData []byte
)

func file_contracts_demand_v1_forecast_events_proto_rawDescGZIP() []byte {
	file_contracts_demand_v1_forecast_events_proto_rawDescOnce.Do(func() {
		file_contracts_demand_v1_forecast_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_demand_v1_forecast_events_proto_rawDesc), len(file_contracts_demand_v1_forecast_events_proto_rawDesc)))
	})
	return file_contracts_demand_v1_forecast_events_proto_rawDescData
}

var file_contracts_demand_v1_forecast_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_demand_v1_forecast_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contracts_demand_v1_forecast_events_proto_goTypes = []any{
	(DemandForecastUpdated_RiskLevel)(0), // 0: demand.v1.DemandForecastUpdated.RiskLevel
	(*DemandForecastUpdated)(nil),        // 1: demand.v1.DemandForecastUpdated
	(*DemandSpikeDetected)(nil),          // 2: demand.v1.DemandSpikeDetected
	(*DemandReorderTriggered)(nil),       // 3: demand.v1.DemandReorderTriggered
	(*v1.EventMetadata)(nil),             // 4: common.v1.EventMetadata
}
var file_contracts_demand_v1_forecast_events_proto_depIdxs = []int32{
	4, // 0: demand.v1.DemandForecastUpdated.metadata:type_name -> common.v1.EventMetadata
	0, // 1: demand.v1.DemandForecastUpdated.risk:type_name -> demand.v1.DemandForecastUpdated.RiskLevel
	4, // 2: demand.v1.DemandSpikeDetected.metadata:type_name -> common.v1.EventMetadata
	4, // 3: demand.v1.DemandReorderTriggered.metadata:type_name -> common.v1.EventMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_contracts_demand_v1_forecast_events_proto_init() }
func file_contracts_demand_v1_forecast_events_proto_init() {
	if File_contracts_demand_v1_forecast_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_demand_v1_forecast_events_proto_rawDesc), len(file_contracts_demand_v1_forecast_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_demand_v1_forecast_events_proto_goTypes,
		DependencyIndexes: file_contracts_demand_v1_forecast_events_proto_depIdxs,
		EnumInfos:         file_contracts_demand_v1_forecast_events_proto_enumTypes,
		MessageInfos:      file_contracts_demand_v1_forecast_events_proto_msgTypes,
	}.Build()
	File_contracts_demand_v1_forecast_events_proto = out.File
	file_contracts_demand_v1_forecast_events_proto_goTypes = nil
	file_contracts_demand_v1_forecast_events_proto_depIdxs = nil
}
