syntax = "proto3";

package shipment.v1;

import "contracts/common/v1/metadata.proto";

option go_package = "contracts/shipment/v1;shipment";

message ShipmentCreated {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  string order_id = 3;
  string warehouse_id = 4;
  string sku = 5;
  int64 quantity = 6;

  string destination_id = 7;
  int64 expected_delivery_time = 8;
}



message ShipmentArrived {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  string destination_id = 3;
  string sku = 4;
  int64 quantity = 5;
  int64 occurred_at = 6;
}

message ShipmentCancelled {
  common.v1.EventMetadata metadata = 1;

  string order_id = 2;
  string warehouse_id = 3;

  string shipment_id = 4;
  string destination_id = 5;
  string sku = 6;
  int64 quantity = 7;
  int64 occurred_at = 8;
}

message ShipmentLocationUpdated {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  double latitude = 3;
  double longitude = 4;
}

message ShipmentDelayed {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  int64 delay_minutes = 3;
  string reason = 4;
}

//====================================================================================================

// Shipment picked up from warehouse
message ShipmentPickedUp {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  string origin_warehouse_id = 3;
}

// Shipment actively in transit
message ShipmentInTransit {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
}

// Shipment delivered successfully
message ShipmentDelivered {
  common.v1.EventMetadata metadata = 1;

  string order_id = 2;
  string warehouse_id = 3;
  string sku = 4;
  int64 quantity = 5;

  string shipment_id = 6;
  string destination_id = 7;
}

// Shipment returned to origin
message ShipmentReturned {
  common.v1.EventMetadata metadata = 1;

  string shipment_id = 2;
  string origin_warehouse_id = 3;
}
