// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contracts/inventory/v1/inventory_events.proto

package inventory

import (
	v1 "github.com/kamogelosekhukhune777/real-time-supply-chain/services/inventory/internal/service/events/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryUpdated_UpdateReason int32

const (
	InventoryUpdated_UPDATE_REASON_UNSPECIFIED InventoryUpdated_UpdateReason = 0
	InventoryUpdated_ORDER_PLACED              InventoryUpdated_UpdateReason = 1
	InventoryUpdated_ORDER_CANCELLED           InventoryUpdated_UpdateReason = 2
	InventoryUpdated_SHIPMENT_RECEIVED         InventoryUpdated_UpdateReason = 3
	InventoryUpdated_SHIPMENT_DISPATCHED       InventoryUpdated_UpdateReason = 4
	InventoryUpdated_REALLOCATION              InventoryUpdated_UpdateReason = 5
	InventoryUpdated_MANUAL_ADJUSTMENT         InventoryUpdated_UpdateReason = 6
)

// Enum value maps for InventoryUpdated_UpdateReason.
var (
	InventoryUpdated_UpdateReason_name = map[int32]string{
		0: "UPDATE_REASON_UNSPECIFIED",
		1: "ORDER_PLACED",
		2: "ORDER_CANCELLED",
		3: "SHIPMENT_RECEIVED",
		4: "SHIPMENT_DISPATCHED",
		5: "REALLOCATION",
		6: "MANUAL_ADJUSTMENT",
	}
	InventoryUpdated_UpdateReason_value = map[string]int32{
		"UPDATE_REASON_UNSPECIFIED": 0,
		"ORDER_PLACED":              1,
		"ORDER_CANCELLED":           2,
		"SHIPMENT_RECEIVED":         3,
		"SHIPMENT_DISPATCHED":       4,
		"REALLOCATION":              5,
		"MANUAL_ADJUSTMENT":         6,
	}
)

func (x InventoryUpdated_UpdateReason) Enum() *InventoryUpdated_UpdateReason {
	p := new(InventoryUpdated_UpdateReason)
	*p = x
	return p
}

func (x InventoryUpdated_UpdateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryUpdated_UpdateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_inventory_v1_inventory_events_proto_enumTypes[0].Descriptor()
}

func (InventoryUpdated_UpdateReason) Type() protoreflect.EnumType {
	return &file_contracts_inventory_v1_inventory_events_proto_enumTypes[0]
}

func (x InventoryUpdated_UpdateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryUpdated_UpdateReason.Descriptor instead.
func (InventoryUpdated_UpdateReason) EnumDescriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{0, 0}
}

type InventoryLowStock_Severity int32

const (
	InventoryLowStock_SEVERITY_UNSPECIFIED InventoryLowStock_Severity = 0
	InventoryLowStock_WARNING              InventoryLowStock_Severity = 1
	InventoryLowStock_CRITICAL             InventoryLowStock_Severity = 2
)

// Enum value maps for InventoryLowStock_Severity.
var (
	InventoryLowStock_Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "WARNING",
		2: "CRITICAL",
	}
	InventoryLowStock_Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"WARNING":              1,
		"CRITICAL":             2,
	}
)

func (x InventoryLowStock_Severity) Enum() *InventoryLowStock_Severity {
	p := new(InventoryLowStock_Severity)
	*p = x
	return p
}

func (x InventoryLowStock_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryLowStock_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_inventory_v1_inventory_events_proto_enumTypes[1].Descriptor()
}

func (InventoryLowStock_Severity) Type() protoreflect.EnumType {
	return &file_contracts_inventory_v1_inventory_events_proto_enumTypes[1]
}

func (x InventoryLowStock_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryLowStock_Severity.Descriptor instead.
func (InventoryLowStock_Severity) EnumDescriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{1, 0}
}

type InventoryReservationReleased_ReleaseReason int32

const (
	InventoryReservationReleased_RELEASE_REASON_UNSPECIFIED InventoryReservationReleased_ReleaseReason = 0
	InventoryReservationReleased_ORDER_CANCELLED            InventoryReservationReleased_ReleaseReason = 1
	InventoryReservationReleased_PAYMENT_FAILED             InventoryReservationReleased_ReleaseReason = 2
	InventoryReservationReleased_RESERVATION_EXPIRED        InventoryReservationReleased_ReleaseReason = 3
)

// Enum value maps for InventoryReservationReleased_ReleaseReason.
var (
	InventoryReservationReleased_ReleaseReason_name = map[int32]string{
		0: "RELEASE_REASON_UNSPECIFIED",
		1: "ORDER_CANCELLED",
		2: "PAYMENT_FAILED",
		3: "RESERVATION_EXPIRED",
	}
	InventoryReservationReleased_ReleaseReason_value = map[string]int32{
		"RELEASE_REASON_UNSPECIFIED": 0,
		"ORDER_CANCELLED":            1,
		"PAYMENT_FAILED":             2,
		"RESERVATION_EXPIRED":        3,
	}
)

func (x InventoryReservationReleased_ReleaseReason) Enum() *InventoryReservationReleased_ReleaseReason {
	p := new(InventoryReservationReleased_ReleaseReason)
	*p = x
	return p
}

func (x InventoryReservationReleased_ReleaseReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryReservationReleased_ReleaseReason) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_inventory_v1_inventory_events_proto_enumTypes[2].Descriptor()
}

func (InventoryReservationReleased_ReleaseReason) Type() protoreflect.EnumType {
	return &file_contracts_inventory_v1_inventory_events_proto_enumTypes[2]
}

func (x InventoryReservationReleased_ReleaseReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryReservationReleased_ReleaseReason.Descriptor instead.
func (InventoryReservationReleased_ReleaseReason) EnumDescriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{4, 0}
}

type InventoryReallocated_ReallocationReason int32

const (
	InventoryReallocated_REALLOCATION_REASON_UNSPECIFIED InventoryReallocated_ReallocationReason = 0
	InventoryReallocated_DEMAND_SPIKE                    InventoryReallocated_ReallocationReason = 1
	InventoryReallocated_OPTIMIZATION_DECISION           InventoryReallocated_ReallocationReason = 2
	InventoryReallocated_MANUAL_OVERRIDE                 InventoryReallocated_ReallocationReason = 3
)

// Enum value maps for InventoryReallocated_ReallocationReason.
var (
	InventoryReallocated_ReallocationReason_name = map[int32]string{
		0: "REALLOCATION_REASON_UNSPECIFIED",
		1: "DEMAND_SPIKE",
		2: "OPTIMIZATION_DECISION",
		3: "MANUAL_OVERRIDE",
	}
	InventoryReallocated_ReallocationReason_value = map[string]int32{
		"REALLOCATION_REASON_UNSPECIFIED": 0,
		"DEMAND_SPIKE":                    1,
		"OPTIMIZATION_DECISION":           2,
		"MANUAL_OVERRIDE":                 3,
	}
)

func (x InventoryReallocated_ReallocationReason) Enum() *InventoryReallocated_ReallocationReason {
	p := new(InventoryReallocated_ReallocationReason)
	*p = x
	return p
}

func (x InventoryReallocated_ReallocationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryReallocated_ReallocationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_inventory_v1_inventory_events_proto_enumTypes[3].Descriptor()
}

func (InventoryReallocated_ReallocationReason) Type() protoreflect.EnumType {
	return &file_contracts_inventory_v1_inventory_events_proto_enumTypes[3]
}

func (x InventoryReallocated_ReallocationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryReallocated_ReallocationReason.Descriptor instead.
func (InventoryReallocated_ReallocationReason) EnumDescriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{5, 0}
}

// Emitted whenever inventory quantities change
type InventoryUpdated struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	Metadata          *v1.EventMetadata             `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId       string                        `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku               string                        `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	QuantityAvailable int32                         `protobuf:"varint,4,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	QuantityReserved  int32                         `protobuf:"varint,5,opt,name=quantity_reserved,json=quantityReserved,proto3" json:"quantity_reserved,omitempty"`
	QuantityIncoming  int32                         `protobuf:"varint,6,opt,name=quantity_incoming,json=quantityIncoming,proto3" json:"quantity_incoming,omitempty"`
	Reason            InventoryUpdated_UpdateReason `protobuf:"varint,7,opt,name=reason,proto3,enum=inventory.v1.InventoryUpdated_UpdateReason" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InventoryUpdated) Reset() {
	*x = InventoryUpdated{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUpdated) ProtoMessage() {}

func (x *InventoryUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUpdated.ProtoReflect.Descriptor instead.
func (*InventoryUpdated) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryUpdated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryUpdated) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryUpdated) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryUpdated) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *InventoryUpdated) GetQuantityReserved() int32 {
	if x != nil {
		return x.QuantityReserved
	}
	return 0
}

func (x *InventoryUpdated) GetQuantityIncoming() int32 {
	if x != nil {
		return x.QuantityIncoming
	}
	return 0
}

func (x *InventoryUpdated) GetReason() InventoryUpdated_UpdateReason {
	if x != nil {
		return x.Reason
	}
	return InventoryUpdated_UPDATE_REASON_UNSPECIFIED
}

// Emitted when available stock drops below configured threshold
type InventoryLowStock struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Metadata          *v1.EventMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId       string                     `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku               string                     `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	QuantityAvailable int32                      `protobuf:"varint,4,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	Threshold         int32                      `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Severity          InventoryLowStock_Severity `protobuf:"varint,6,opt,name=severity,proto3,enum=inventory.v1.InventoryLowStock_Severity" json:"severity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InventoryLowStock) Reset() {
	*x = InventoryLowStock{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryLowStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryLowStock) ProtoMessage() {}

func (x *InventoryLowStock) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryLowStock.ProtoReflect.Descriptor instead.
func (*InventoryLowStock) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryLowStock) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryLowStock) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryLowStock) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryLowStock) GetQuantityAvailable() int32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *InventoryLowStock) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *InventoryLowStock) GetSeverity() InventoryLowStock_Severity {
	if x != nil {
		return x.Severity
	}
	return InventoryLowStock_SEVERITY_UNSPECIFIED
}

// Emitted when available stock reaches zero
type InventoryOutOfStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryOutOfStock) Reset() {
	*x = InventoryOutOfStock{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryOutOfStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryOutOfStock) ProtoMessage() {}

func (x *InventoryOutOfStock) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryOutOfStock.ProtoReflect.Descriptor instead.
func (*InventoryOutOfStock) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryOutOfStock) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryOutOfStock) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryOutOfStock) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// Emitted when stock is reserved for an order
type InventoryReserved struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Metadata               *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId            string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku                    string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ReservationId          string                 `protobuf:"bytes,4,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId                string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReservedQuantity       int32                  `protobuf:"varint,6,opt,name=reserved_quantity,json=reservedQuantity,proto3" json:"reserved_quantity,omitempty"`
	QuantityAvailableAfter int32                  `protobuf:"varint,7,opt,name=quantity_available_after,json=quantityAvailableAfter,proto3" json:"quantity_available_after,omitempty"`
	QuantityReservedAfter  int32                  `protobuf:"varint,8,opt,name=quantity_reserved_after,json=quantityReservedAfter,proto3" json:"quantity_reserved_after,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InventoryReserved) Reset() {
	*x = InventoryReserved{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReserved) ProtoMessage() {}

func (x *InventoryReserved) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReserved.ProtoReflect.Descriptor instead.
func (*InventoryReserved) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryReserved) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryReserved) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryReserved) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryReserved) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *InventoryReserved) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReserved) GetReservedQuantity() int32 {
	if x != nil {
		return x.ReservedQuantity
	}
	return 0
}

func (x *InventoryReserved) GetQuantityAvailableAfter() int32 {
	if x != nil {
		return x.QuantityAvailableAfter
	}
	return 0
}

func (x *InventoryReserved) GetQuantityReservedAfter() int32 {
	if x != nil {
		return x.QuantityReservedAfter
	}
	return 0
}

// Emitted when a reservation is released (cancelled / expired)
type InventoryReservationReleased struct {
	state                  protoimpl.MessageState                     `protogen:"open.v1"`
	Metadata               *v1.EventMetadata                          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId            string                                     `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku                    string                                     `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ReservationId          string                                     `protobuf:"bytes,4,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId                string                                     `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ReleasedQuantity       int32                                      `protobuf:"varint,6,opt,name=released_quantity,json=releasedQuantity,proto3" json:"released_quantity,omitempty"`
	QuantityAvailableAfter int32                                      `protobuf:"varint,7,opt,name=quantity_available_after,json=quantityAvailableAfter,proto3" json:"quantity_available_after,omitempty"`
	QuantityReservedAfter  int32                                      `protobuf:"varint,8,opt,name=quantity_reserved_after,json=quantityReservedAfter,proto3" json:"quantity_reserved_after,omitempty"`
	Reason                 InventoryReservationReleased_ReleaseReason `protobuf:"varint,9,opt,name=reason,proto3,enum=inventory.v1.InventoryReservationReleased_ReleaseReason" json:"reason,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InventoryReservationReleased) Reset() {
	*x = InventoryReservationReleased{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReservationReleased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReservationReleased) ProtoMessage() {}

func (x *InventoryReservationReleased) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReservationReleased.ProtoReflect.Descriptor instead.
func (*InventoryReservationReleased) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{4}
}

func (x *InventoryReservationReleased) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryReservationReleased) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryReservationReleased) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryReservationReleased) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *InventoryReservationReleased) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *InventoryReservationReleased) GetReleasedQuantity() int32 {
	if x != nil {
		return x.ReleasedQuantity
	}
	return 0
}

func (x *InventoryReservationReleased) GetQuantityAvailableAfter() int32 {
	if x != nil {
		return x.QuantityAvailableAfter
	}
	return 0
}

func (x *InventoryReservationReleased) GetQuantityReservedAfter() int32 {
	if x != nil {
		return x.QuantityReservedAfter
	}
	return 0
}

func (x *InventoryReservationReleased) GetReason() InventoryReservationReleased_ReleaseReason {
	if x != nil {
		return x.Reason
	}
	return InventoryReservationReleased_RELEASE_REASON_UNSPECIFIED
}

// Emitted when inventory is reallocated between warehouses
type InventoryReallocated struct {
	state           protoimpl.MessageState                  `protogen:"open.v1"`
	Metadata        *v1.EventMetadata                       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sku             string                                  `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	FromWarehouseId string                                  `protobuf:"bytes,3,opt,name=from_warehouse_id,json=fromWarehouseId,proto3" json:"from_warehouse_id,omitempty"`
	ToWarehouseId   string                                  `protobuf:"bytes,4,opt,name=to_warehouse_id,json=toWarehouseId,proto3" json:"to_warehouse_id,omitempty"`
	Quantity        int32                                   `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Reason          InventoryReallocated_ReallocationReason `protobuf:"varint,6,opt,name=reason,proto3,enum=inventory.v1.InventoryReallocated_ReallocationReason" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryReallocated) Reset() {
	*x = InventoryReallocated{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReallocated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReallocated) ProtoMessage() {}

func (x *InventoryReallocated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReallocated.ProtoReflect.Descriptor instead.
func (*InventoryReallocated) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{5}
}

func (x *InventoryReallocated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryReallocated) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryReallocated) GetFromWarehouseId() string {
	if x != nil {
		return x.FromWarehouseId
	}
	return ""
}

func (x *InventoryReallocated) GetToWarehouseId() string {
	if x != nil {
		return x.ToWarehouseId
	}
	return ""
}

func (x *InventoryReallocated) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryReallocated) GetReason() InventoryReallocated_ReallocationReason {
	if x != nil {
		return x.Reason
	}
	return InventoryReallocated_REALLOCATION_REASON_UNSPECIFIED
}

// reservation attempt failed
type InventoryReservationFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryReservationFailed) Reset() {
	*x = InventoryReservationFailed{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryReservationFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryReservationFailed) ProtoMessage() {}

func (x *InventoryReservationFailed) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryReservationFailed.ProtoReflect.Descriptor instead.
func (*InventoryReservationFailed) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{6}
}

func (x *InventoryReservationFailed) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryReservationFailed) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryReservationFailed) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// inventory shortage detected
type InventoryShortageDetected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryShortageDetected) Reset() {
	*x = InventoryShortageDetected{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryShortageDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryShortageDetected) ProtoMessage() {}

func (x *InventoryShortageDetected) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryShortageDetected.ProtoReflect.Descriptor instead.
func (*InventoryShortageDetected) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{7}
}

func (x *InventoryShortageDetected) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryShortageDetected) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryShortageDetected) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

// transfer lifecycle (important for shipment + optimization)
type InventoryTransferStarted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metadata        *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sku             string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	FromWarehouseId string                 `protobuf:"bytes,3,opt,name=from_warehouse_id,json=fromWarehouseId,proto3" json:"from_warehouse_id,omitempty"`
	ToWarehouseId   string                 `protobuf:"bytes,4,opt,name=to_warehouse_id,json=toWarehouseId,proto3" json:"to_warehouse_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryTransferStarted) Reset() {
	*x = InventoryTransferStarted{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryTransferStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryTransferStarted) ProtoMessage() {}

func (x *InventoryTransferStarted) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryTransferStarted.ProtoReflect.Descriptor instead.
func (*InventoryTransferStarted) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{8}
}

func (x *InventoryTransferStarted) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryTransferStarted) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryTransferStarted) GetFromWarehouseId() string {
	if x != nil {
		return x.FromWarehouseId
	}
	return ""
}

func (x *InventoryTransferStarted) GetToWarehouseId() string {
	if x != nil {
		return x.ToWarehouseId
	}
	return ""
}

type InventoryTransferCompleted struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Metadata        *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Sku             string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	FromWarehouseId string                 `protobuf:"bytes,3,opt,name=from_warehouse_id,json=fromWarehouseId,proto3" json:"from_warehouse_id,omitempty"`
	ToWarehouseId   string                 `protobuf:"bytes,4,opt,name=to_warehouse_id,json=toWarehouseId,proto3" json:"to_warehouse_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventoryTransferCompleted) Reset() {
	*x = InventoryTransferCompleted{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryTransferCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryTransferCompleted) ProtoMessage() {}

func (x *InventoryTransferCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryTransferCompleted.ProtoReflect.Descriptor instead.
func (*InventoryTransferCompleted) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{9}
}

func (x *InventoryTransferCompleted) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryTransferCompleted) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryTransferCompleted) GetFromWarehouseId() string {
	if x != nil {
		return x.FromWarehouseId
	}
	return ""
}

func (x *InventoryTransferCompleted) GetToWarehouseId() string {
	if x != nil {
		return x.ToWarehouseId
	}
	return ""
}

// manual/system correction
type InventoryAdjusted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryAdjusted) Reset() {
	*x = InventoryAdjusted{}
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryAdjusted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryAdjusted) ProtoMessage() {}

func (x *InventoryAdjusted) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_inventory_v1_inventory_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryAdjusted.ProtoReflect.Descriptor instead.
func (*InventoryAdjusted) Descriptor() ([]byte, []int) {
	return file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP(), []int{10}
}

func (x *InventoryAdjusted) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InventoryAdjusted) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *InventoryAdjusted) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

var File_contracts_inventory_v1_inventory_events_proto protoreflect.FileDescriptor

const file_contracts_inventory_v1_inventory_events_proto_rawDesc = "" +
	"\n" +
	"-contracts/inventory/v1/inventory_events.proto\x12\finventory.v1\x1a\"contracts/common/v1/metadata.proto\"\xfb\x03\n" +
	"\x10InventoryUpdated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12-\n" +
	"\x12quantity_available\x18\x04 \x01(\x05R\x11quantityAvailable\x12+\n" +
	"\x11quantity_reserved\x18\x05 \x01(\x05R\x10quantityReserved\x12+\n" +
	"\x11quantity_incoming\x18\x06 \x01(\x05R\x10quantityIncoming\x12C\n" +
	"\x06reason\x18\a \x01(\x0e2+.inventory.v1.InventoryUpdated.UpdateReasonR\x06reason\"\xad\x01\n" +
	"\fUpdateReason\x12\x1d\n" +
	"\x19UPDATE_REASON_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fORDER_PLACED\x10\x01\x12\x13\n" +
	"\x0fORDER_CANCELLED\x10\x02\x12\x15\n" +
	"\x11SHIPMENT_RECEIVED\x10\x03\x12\x17\n" +
	"\x13SHIPMENT_DISPATCHED\x10\x04\x12\x10\n" +
	"\fREALLOCATION\x10\x05\x12\x15\n" +
	"\x11MANUAL_ADJUSTMENT\x10\x06\"\xd2\x02\n" +
	"\x11InventoryLowStock\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12-\n" +
	"\x12quantity_available\x18\x04 \x01(\x05R\x11quantityAvailable\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12D\n" +
	"\bseverity\x18\x06 \x01(\x0e2(.inventory.v1.InventoryLowStock.SeverityR\bseverity\"?\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aWARNING\x10\x01\x12\f\n" +
	"\bCRITICAL\x10\x02\"\x80\x01\n" +
	"\x13InventoryOutOfStock\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"\xdf\x02\n" +
	"\x11InventoryReserved\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12%\n" +
	"\x0ereservation_id\x18\x04 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12+\n" +
	"\x11reserved_quantity\x18\x06 \x01(\x05R\x10reservedQuantity\x128\n" +
	"\x18quantity_available_after\x18\a \x01(\x05R\x16quantityAvailableAfter\x126\n" +
	"\x17quantity_reserved_after\x18\b \x01(\x05R\x15quantityReservedAfter\"\xaf\x04\n" +
	"\x1cInventoryReservationReleased\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12%\n" +
	"\x0ereservation_id\x18\x04 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12+\n" +
	"\x11released_quantity\x18\x06 \x01(\x05R\x10releasedQuantity\x128\n" +
	"\x18quantity_available_after\x18\a \x01(\x05R\x16quantityAvailableAfter\x126\n" +
	"\x17quantity_reserved_after\x18\b \x01(\x05R\x15quantityReservedAfter\x12P\n" +
	"\x06reason\x18\t \x01(\x0e28.inventory.v1.InventoryReservationReleased.ReleaseReasonR\x06reason\"q\n" +
	"\rReleaseReason\x12\x1e\n" +
	"\x1aRELEASE_REASON_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fORDER_CANCELLED\x10\x01\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\x02\x12\x17\n" +
	"\x13RESERVATION_EXPIRED\x10\x03\"\x9a\x03\n" +
	"\x14InventoryReallocated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12*\n" +
	"\x11from_warehouse_id\x18\x03 \x01(\tR\x0ffromWarehouseId\x12&\n" +
	"\x0fto_warehouse_id\x18\x04 \x01(\tR\rtoWarehouseId\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\x12M\n" +
	"\x06reason\x18\x06 \x01(\x0e25.inventory.v1.InventoryReallocated.ReallocationReasonR\x06reason\"{\n" +
	"\x12ReallocationReason\x12#\n" +
	"\x1fREALLOCATION_REASON_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fDEMAND_SPIKE\x10\x01\x12\x19\n" +
	"\x15OPTIMIZATION_DECISION\x10\x02\x12\x13\n" +
	"\x0fMANUAL_OVERRIDE\x10\x03\"\x87\x01\n" +
	"\x1aInventoryReservationFailed\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"\x86\x01\n" +
	"\x19InventoryShortageDetected\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\"\xb6\x01\n" +
	"\x18InventoryTransferStarted\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12*\n" +
	"\x11from_warehouse_id\x18\x03 \x01(\tR\x0ffromWarehouseId\x12&\n" +
	"\x0fto_warehouse_id\x18\x04 \x01(\tR\rtoWarehouseId\"\xb8\x01\n" +
	"\x1aInventoryTransferCompleted\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12*\n" +
	"\x11from_warehouse_id\x18\x03 \x01(\tR\x0ffromWarehouseId\x12&\n" +
	"\x0fto_warehouse_id\x18\x04 \x01(\tR\rtoWarehouseId\"~\n" +
	"\x11InventoryAdjusted\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03skuB\"Z contracts/inventory/v1;inventoryb\x06proto3"

var (
	file_contracts_inventory_v1_inventory_events_proto_rawDescOnce sync.Once
	file_contracts_inventory_v1_inventory_events_proto_rawDescData []byte
)

func file_contracts_inventory_v1_inventory_events_proto_rawDescGZIP() []byte {
	file_contracts_inventory_v1_inventory_events_proto_rawDescOnce.Do(func() {
		file_contracts_inventory_v1_inventory_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_inventory_v1_inventory_events_proto_rawDesc), len(file_contracts_inventory_v1_inventory_events_proto_rawDesc)))
	})
	return file_contracts_inventory_v1_inventory_events_proto_rawDescData
}

var file_contracts_inventory_v1_inventory_events_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_contracts_inventory_v1_inventory_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_contracts_inventory_v1_inventory_events_proto_goTypes = []any{
	(InventoryUpdated_UpdateReason)(0),              // 0: inventory.v1.InventoryUpdated.UpdateReason
	(InventoryLowStock_Severity)(0),                 // 1: inventory.v1.InventoryLowStock.Severity
	(InventoryReservationReleased_ReleaseReason)(0), // 2: inventory.v1.InventoryReservationReleased.ReleaseReason
	(InventoryReallocated_ReallocationReason)(0),    // 3: inventory.v1.InventoryReallocated.ReallocationReason
	(*InventoryUpdated)(nil),                        // 4: inventory.v1.InventoryUpdated
	(*InventoryLowStock)(nil),                       // 5: inventory.v1.InventoryLowStock
	(*InventoryOutOfStock)(nil),                     // 6: inventory.v1.InventoryOutOfStock
	(*InventoryReserved)(nil),                       // 7: inventory.v1.InventoryReserved
	(*InventoryReservationReleased)(nil),            // 8: inventory.v1.InventoryReservationReleased
	(*InventoryReallocated)(nil),                    // 9: inventory.v1.InventoryReallocated
	(*InventoryReservationFailed)(nil),              // 10: inventory.v1.InventoryReservationFailed
	(*InventoryShortageDetected)(nil),               // 11: inventory.v1.InventoryShortageDetected
	(*InventoryTransferStarted)(nil),                // 12: inventory.v1.InventoryTransferStarted
	(*InventoryTransferCompleted)(nil),              // 13: inventory.v1.InventoryTransferCompleted
	(*InventoryAdjusted)(nil),                       // 14: inventory.v1.InventoryAdjusted
	(*v1.EventMetadata)(nil),                        // 15: common.v1.EventMetadata
}
var file_contracts_inventory_v1_inventory_events_proto_depIdxs = []int32{
	15, // 0: inventory.v1.InventoryUpdated.metadata:type_name -> common.v1.EventMetadata
	0,  // 1: inventory.v1.InventoryUpdated.reason:type_name -> inventory.v1.InventoryUpdated.UpdateReason
	15, // 2: inventory.v1.InventoryLowStock.metadata:type_name -> common.v1.EventMetadata
	1,  // 3: inventory.v1.InventoryLowStock.severity:type_name -> inventory.v1.InventoryLowStock.Severity
	15, // 4: inventory.v1.InventoryOutOfStock.metadata:type_name -> common.v1.EventMetadata
	15, // 5: inventory.v1.InventoryReserved.metadata:type_name -> common.v1.EventMetadata
	15, // 6: inventory.v1.InventoryReservationReleased.metadata:type_name -> common.v1.EventMetadata
	2,  // 7: inventory.v1.InventoryReservationReleased.reason:type_name -> inventory.v1.InventoryReservationReleased.ReleaseReason
	15, // 8: inventory.v1.InventoryReallocated.metadata:type_name -> common.v1.EventMetadata
	3,  // 9: inventory.v1.InventoryReallocated.reason:type_name -> inventory.v1.InventoryReallocated.ReallocationReason
	15, // 10: inventory.v1.InventoryReservationFailed.metadata:type_name -> common.v1.EventMetadata
	15, // 11: inventory.v1.InventoryShortageDetected.metadata:type_name -> common.v1.EventMetadata
	15, // 12: inventory.v1.InventoryTransferStarted.metadata:type_name -> common.v1.EventMetadata
	15, // 13: inventory.v1.InventoryTransferCompleted.metadata:type_name -> common.v1.EventMetadata
	15, // 14: inventory.v1.InventoryAdjusted.metadata:type_name -> common.v1.EventMetadata
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_contracts_inventory_v1_inventory_events_proto_init() }
func file_contracts_inventory_v1_inventory_events_proto_init() {
	if File_contracts_inventory_v1_inventory_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_inventory_v1_inventory_events_proto_rawDesc), len(file_contracts_inventory_v1_inventory_events_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_inventory_v1_inventory_events_proto_goTypes,
		DependencyIndexes: file_contracts_inventory_v1_inventory_events_proto_depIdxs,
		EnumInfos:         file_contracts_inventory_v1_inventory_events_proto_enumTypes,
		MessageInfos:      file_contracts_inventory_v1_inventory_events_proto_msgTypes,
	}.Build()
	File_contracts_inventory_v1_inventory_events_proto = out.File
	file_contracts_inventory_v1_inventory_events_proto_goTypes = nil
	file_contracts_inventory_v1_inventory_events_proto_depIdxs = nil
}
