// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: contracts/shipment/v1/shipment_events.proto

package shipment

import (
	v1 "github.com/kamogelosekhukhune777/real-time-supply-chain/services/inventory/internal/service/events/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentCreated struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Metadata             *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId           string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OrderId              string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WarehouseId          string                 `protobuf:"bytes,4,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku                  string                 `protobuf:"bytes,5,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity             int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	DestinationId        string                 `protobuf:"bytes,7,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	ExpectedDeliveryTime int64                  `protobuf:"varint,8,opt,name=expected_delivery_time,json=expectedDeliveryTime,proto3" json:"expected_delivery_time,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ShipmentCreated) Reset() {
	*x = ShipmentCreated{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentCreated) ProtoMessage() {}

func (x *ShipmentCreated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentCreated.ProtoReflect.Descriptor instead.
func (*ShipmentCreated) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{0}
}

func (x *ShipmentCreated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentCreated) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentCreated) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ShipmentCreated) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentCreated) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShipmentCreated) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *ShipmentCreated) GetExpectedDeliveryTime() int64 {
	if x != nil {
		return x.ExpectedDeliveryTime
	}
	return 0
}

type ShipmentArrived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentArrived) Reset() {
	*x = ShipmentArrived{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentArrived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentArrived) ProtoMessage() {}

func (x *ShipmentArrived) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentArrived.ProtoReflect.Descriptor instead.
func (*ShipmentArrived) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{1}
}

func (x *ShipmentArrived) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentArrived) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentArrived) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *ShipmentArrived) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentArrived) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShipmentArrived) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type ShipmentCancelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,4,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,5,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OccurredAt    int64                  `protobuf:"varint,8,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentCancelled) Reset() {
	*x = ShipmentCancelled{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentCancelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentCancelled) ProtoMessage() {}

func (x *ShipmentCancelled) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentCancelled.ProtoReflect.Descriptor instead.
func (*ShipmentCancelled) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{2}
}

func (x *ShipmentCancelled) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentCancelled) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentCancelled) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ShipmentCancelled) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentCancelled) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *ShipmentCancelled) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentCancelled) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShipmentCancelled) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

type ShipmentLocationUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentLocationUpdated) Reset() {
	*x = ShipmentLocationUpdated{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentLocationUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentLocationUpdated) ProtoMessage() {}

func (x *ShipmentLocationUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentLocationUpdated.ProtoReflect.Descriptor instead.
func (*ShipmentLocationUpdated) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentLocationUpdated) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentLocationUpdated) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentLocationUpdated) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *ShipmentLocationUpdated) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ShipmentDelayed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	DelayMinutes  int64                  `protobuf:"varint,3,opt,name=delay_minutes,json=delayMinutes,proto3" json:"delay_minutes,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentDelayed) Reset() {
	*x = ShipmentDelayed{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDelayed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDelayed) ProtoMessage() {}

func (x *ShipmentDelayed) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDelayed.ProtoReflect.Descriptor instead.
func (*ShipmentDelayed) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{4}
}

func (x *ShipmentDelayed) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentDelayed) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentDelayed) GetDelayMinutes() int64 {
	if x != nil {
		return x.DelayMinutes
	}
	return 0
}

func (x *ShipmentDelayed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Shipment picked up from warehouse
type ShipmentPickedUp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Metadata          *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId        string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OriginWarehouseId string                 `protobuf:"bytes,3,opt,name=origin_warehouse_id,json=originWarehouseId,proto3" json:"origin_warehouse_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShipmentPickedUp) Reset() {
	*x = ShipmentPickedUp{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentPickedUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentPickedUp) ProtoMessage() {}

func (x *ShipmentPickedUp) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentPickedUp.ProtoReflect.Descriptor instead.
func (*ShipmentPickedUp) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{5}
}

func (x *ShipmentPickedUp) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentPickedUp) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentPickedUp) GetOriginWarehouseId() string {
	if x != nil {
		return x.OriginWarehouseId
	}
	return ""
}

// Shipment actively in transit
type ShipmentInTransit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentInTransit) Reset() {
	*x = ShipmentInTransit{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentInTransit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentInTransit) ProtoMessage() {}

func (x *ShipmentInTransit) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentInTransit.ProtoReflect.Descriptor instead.
func (*ShipmentInTransit) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{6}
}

func (x *ShipmentInTransit) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentInTransit) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

// Shipment delivered successfully
type ShipmentDelivered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Sku           string                 `protobuf:"bytes,4,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int64                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,6,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	DestinationId string                 `protobuf:"bytes,7,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentDelivered) Reset() {
	*x = ShipmentDelivered{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDelivered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDelivered) ProtoMessage() {}

func (x *ShipmentDelivered) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDelivered.ProtoReflect.Descriptor instead.
func (*ShipmentDelivered) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{7}
}

func (x *ShipmentDelivered) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentDelivered) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentDelivered) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ShipmentDelivered) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ShipmentDelivered) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShipmentDelivered) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentDelivered) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

// Shipment returned to origin
type ShipmentReturned struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Metadata          *v1.EventMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ShipmentId        string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	OriginWarehouseId string                 `protobuf:"bytes,3,opt,name=origin_warehouse_id,json=originWarehouseId,proto3" json:"origin_warehouse_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShipmentReturned) Reset() {
	*x = ShipmentReturned{}
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentReturned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentReturned) ProtoMessage() {}

func (x *ShipmentReturned) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_shipment_v1_shipment_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentReturned.ProtoReflect.Descriptor instead.
func (*ShipmentReturned) Descriptor() ([]byte, []int) {
	return file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP(), []int{8}
}

func (x *ShipmentReturned) GetMetadata() *v1.EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ShipmentReturned) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentReturned) GetOriginWarehouseId() string {
	if x != nil {
		return x.OriginWarehouseId
	}
	return ""
}

var File_contracts_shipment_v1_shipment_events_proto protoreflect.FileDescriptor

const file_contracts_shipment_v1_shipment_events_proto_rawDesc = "" +
	"\n" +
	"+contracts/shipment/v1/shipment_events.proto\x12\vshipment.v1\x1a\"contracts/common/v1/metadata.proto\"\xb1\x02\n" +
	"\x0fShipmentCreated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12!\n" +
	"\fwarehouse_id\x18\x04 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x05 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\x12%\n" +
	"\x0edestination_id\x18\a \x01(\tR\rdestinationId\x124\n" +
	"\x16expected_delivery_time\x18\b \x01(\x03R\x14expectedDeliveryTime\"\xde\x01\n" +
	"\x0fShipmentArrived\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1f\n" +
	"\voccurred_at\x18\x06 \x01(\x03R\n" +
	"occurredAt\"\x9e\x02\n" +
	"\x11ShipmentCancelled\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\tR\vwarehouseId\x12\x1f\n" +
	"\vshipment_id\x18\x04 \x01(\tR\n" +
	"shipmentId\x12%\n" +
	"\x0edestination_id\x18\x05 \x01(\tR\rdestinationId\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12\x1f\n" +
	"\voccurred_at\x18\b \x01(\x03R\n" +
	"occurredAt\"\xaa\x01\n" +
	"\x17ShipmentLocationUpdated\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\"\xa5\x01\n" +
	"\x0fShipmentDelayed\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12#\n" +
	"\rdelay_minutes\x18\x03 \x01(\x03R\fdelayMinutes\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x99\x01\n" +
	"\x10ShipmentPickedUp\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12.\n" +
	"\x13origin_warehouse_id\x18\x03 \x01(\tR\x11originWarehouseId\"j\n" +
	"\x11ShipmentInTransit\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\"\xfd\x01\n" +
	"\x11ShipmentDelivered\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fwarehouse_id\x18\x03 \x01(\tR\vwarehouseId\x12\x10\n" +
	"\x03sku\x18\x04 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x03R\bquantity\x12\x1f\n" +
	"\vshipment_id\x18\x06 \x01(\tR\n" +
	"shipmentId\x12%\n" +
	"\x0edestination_id\x18\a \x01(\tR\rdestinationId\"\x99\x01\n" +
	"\x10ShipmentReturned\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.common.v1.EventMetadataR\bmetadata\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12.\n" +
	"\x13origin_warehouse_id\x18\x03 \x01(\tR\x11originWarehouseIdB Z\x1econtracts/shipment/v1;shipmentb\x06proto3"

var (
	file_contracts_shipment_v1_shipment_events_proto_rawDescOnce sync.Once
	file_contracts_shipment_v1_shipment_events_proto_rawDescData []byte
)

func file_contracts_shipment_v1_shipment_events_proto_rawDescGZIP() []byte {
	file_contracts_shipment_v1_shipment_events_proto_rawDescOnce.Do(func() {
		file_contracts_shipment_v1_shipment_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contracts_shipment_v1_shipment_events_proto_rawDesc), len(file_contracts_shipment_v1_shipment_events_proto_rawDesc)))
	})
	return file_contracts_shipment_v1_shipment_events_proto_rawDescData
}

var file_contracts_shipment_v1_shipment_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_contracts_shipment_v1_shipment_events_proto_goTypes = []any{
	(*ShipmentCreated)(nil),         // 0: shipment.v1.ShipmentCreated
	(*ShipmentArrived)(nil),         // 1: shipment.v1.ShipmentArrived
	(*ShipmentCancelled)(nil),       // 2: shipment.v1.ShipmentCancelled
	(*ShipmentLocationUpdated)(nil), // 3: shipment.v1.ShipmentLocationUpdated
	(*ShipmentDelayed)(nil),         // 4: shipment.v1.ShipmentDelayed
	(*ShipmentPickedUp)(nil),        // 5: shipment.v1.ShipmentPickedUp
	(*ShipmentInTransit)(nil),       // 6: shipment.v1.ShipmentInTransit
	(*ShipmentDelivered)(nil),       // 7: shipment.v1.ShipmentDelivered
	(*ShipmentReturned)(nil),        // 8: shipment.v1.ShipmentReturned
	(*v1.EventMetadata)(nil),        // 9: common.v1.EventMetadata
}
var file_contracts_shipment_v1_shipment_events_proto_depIdxs = []int32{
	9, // 0: shipment.v1.ShipmentCreated.metadata:type_name -> common.v1.EventMetadata
	9, // 1: shipment.v1.ShipmentArrived.metadata:type_name -> common.v1.EventMetadata
	9, // 2: shipment.v1.ShipmentCancelled.metadata:type_name -> common.v1.EventMetadata
	9, // 3: shipment.v1.ShipmentLocationUpdated.metadata:type_name -> common.v1.EventMetadata
	9, // 4: shipment.v1.ShipmentDelayed.metadata:type_name -> common.v1.EventMetadata
	9, // 5: shipment.v1.ShipmentPickedUp.metadata:type_name -> common.v1.EventMetadata
	9, // 6: shipment.v1.ShipmentInTransit.metadata:type_name -> common.v1.EventMetadata
	9, // 7: shipment.v1.ShipmentDelivered.metadata:type_name -> common.v1.EventMetadata
	9, // 8: shipment.v1.ShipmentReturned.metadata:type_name -> common.v1.EventMetadata
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_contracts_shipment_v1_shipment_events_proto_init() }
func file_contracts_shipment_v1_shipment_events_proto_init() {
	if File_contracts_shipment_v1_shipment_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contracts_shipment_v1_shipment_events_proto_rawDesc), len(file_contracts_shipment_v1_shipment_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_shipment_v1_shipment_events_proto_goTypes,
		DependencyIndexes: file_contracts_shipment_v1_shipment_events_proto_depIdxs,
		MessageInfos:      file_contracts_shipment_v1_shipment_events_proto_msgTypes,
	}.Build()
	File_contracts_shipment_v1_shipment_events_proto = out.File
	file_contracts_shipment_v1_shipment_events_proto_goTypes = nil
	file_contracts_shipment_v1_shipment_events_proto_depIdxs = nil
}
